const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{"01底圖": 0},
	{"01標題": 0},
	{Fade: 0},
	{"01標題2": 0},
	{"01點擊開始": 0},
	{"02底圖": 0},
	{"02標": 0},
	{"02標題2": 0},
	{"02標題": 0},
	{"02標2": 0},
	{"02標3": 0},
	{"02常見問題": 0},
	{"10選單標題": 0},
	{"10選單小標1": 0},
	{"10選單小標2": 0},
	{"10選單小標3": 0},
	{Variable1: 0},
	{"11知識內容": 0},
	{"11影片1": 0},
	{"11影片2": 0},
	{題目: 0},
	{"12左側區塊": 0},
	{"12選項": 0},
	{"12題目": 0},
	{"12選項2": 0},
	{"12選項3": 0},
	{"12選項4": 0},
	{"12貓": 0},
	{X1: 0},
	{Y1: 0},
	{"12選項字": 0},
	{"12選項字2": 0},
	{"12選項字3": 0},
	{"12選項字4": 0},
	{"12詳解": 0},
	{"12下一題": 0},
	{"12題目2": 0},
	{"12對錯": 0},
	{"20選單標題": 0},
	{"20選單小標1": 0},
	{"20選單小標2": 0},
	{"20選單小標3": 0},
	{"21知識內容": 0},
	{"22右側區塊": 0},
	{"22左側區塊": 0},
	{"30選單標題": 0},
	{"30選單小標1": 0},
	{"30選單小標2": 0},
	{"30選單小標3": 0},
	{"31知識內容": 0},
	{"32右側區塊": 0},
	{"32左側區塊": 0},
	{"00屋子": 0},
	{"00回到上一頁": 0},
	{"00選單": 0},
	{"00聲音": 0},
	{"00下一頁": 0},
	{"00上一頁": 0},
	{"00回到選單": 0},
	{"00回選單": 0},
	{"00白色": 0},
	{"00前往測驗": 0},
	{"00播放": 0},
	{"03底圖": 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{small: 0},
	{判斷頁碼: 0},
	{判斷小單元: 0},
	{"03頁數": 0},
	{"11頁數": 0},
	{"12頁數": 0},
	{秒數: 0},
	{"21頁數": 0},
	{"22頁數": 0},
	{"31頁數": 0},
	{"32頁數": 0}
];

self.InstanceType = {
	_01底圖: class extends self.ISpriteInstance {},
	_01標題: class extends self.ISpriteInstance {},
	_01標題2: class extends self.ISpriteInstance {},
	_01點擊開始: class extends self.ITextInstance {},
	_02底圖: class extends self.ISpriteInstance {},
	_02標: class extends self.ISpriteInstance {},
	_02標題2: class extends self.ISpriteInstance {},
	_02標題: class extends self.ISpriteInstance {},
	_02標2: class extends self.ISpriteInstance {},
	_02標3: class extends self.ISpriteInstance {},
	_02常見問題: class extends self.ISpriteInstance {},
	_10選單標題: class extends self.ISpriteInstance {},
	_10選單小標1: class extends self.ISpriteInstance {},
	_10選單小標2: class extends self.ISpriteInstance {},
	_10選單小標3: class extends self.ISpriteInstance {},
	_11知識內容: class extends self.ISpriteInstance {},
	_11影片1: class extends self.IWorldInstance {},
	_11影片2: class extends self.IWorldInstance {},
	_12左側區塊: class extends self.ISpriteInstance {},
	_12選項: class extends self.ISpriteInstance {},
	_12題目: class extends self.ITextInstance {},
	_12選項2: class extends self.ISpriteInstance {},
	_12選項3: class extends self.ISpriteInstance {},
	_12選項4: class extends self.ISpriteInstance {},
	_12貓: class extends self.ISpriteInstance {},
	_12選項字: class extends self.ITextInstance {},
	_12選項字2: class extends self.ITextInstance {},
	_12選項字3: class extends self.ITextInstance {},
	_12選項字4: class extends self.ITextInstance {},
	_12詳解: class extends self.ISpriteInstance {},
	_12下一題: class extends self.ISpriteInstance {},
	_12題目2: class extends self.ITextInstance {},
	_12對錯: class extends self.ISpriteInstance {},
	_20選單標題: class extends self.ISpriteInstance {},
	_20選單小標1: class extends self.ISpriteInstance {},
	_20選單小標2: class extends self.ISpriteInstance {},
	_20選單小標3: class extends self.ISpriteInstance {},
	_21知識內容: class extends self.ISpriteInstance {},
	_22右側區塊: class extends self.ISpriteInstance {},
	_22左側區塊: class extends self.ISpriteInstance {},
	_30選單標題: class extends self.ISpriteInstance {},
	_30選單小標1: class extends self.ISpriteInstance {},
	_30選單小標2: class extends self.ISpriteInstance {},
	_30選單小標3: class extends self.ISpriteInstance {},
	_31知識內容: class extends self.ISpriteInstance {},
	_32右側區塊: class extends self.ISpriteInstance {},
	_32左側區塊: class extends self.ISpriteInstance {},
	_00屋子: class extends self.ISpriteInstance {},
	_00回到上一頁: class extends self.ISpriteInstance {},
	_00選單: class extends self.ISpriteInstance {},
	_00聲音: class extends self.ISpriteInstance {},
	_00下一頁: class extends self.ISpriteInstance {},
	_00上一頁: class extends self.ISpriteInstance {},
	_00回到選單: class extends self.ISpriteInstance {},
	_00回選單: class extends self.ISpriteInstance {},
	_00白色: class extends self.ISpriteInstance {},
	_00前往測驗: class extends self.ISpriteInstance {},
	_00播放: class extends self.ISpriteInstance {},
	_03底圖: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {}
}